### ISSUE TITLE
provider-aws-firehose v0.46.0: impossible to sync existing DeliveryStream resources

### ISSUE THREAD

**Issue by sannaroby** [upbound/provider-aws#1026]
### What happened?
I've update the provider-aws-firehose from v0.41.0 to 0.46.0 and all already existing DeliveryStream resources can't be synchronized.
In the "status" of the resources, I can see this error:

`- lastTransitionTime: '2023-12-15T11:17:46Z'
      message: >-
        observe failed: cannot get connection details: cannot get connection
        details: cannot expand wildcards: cannot expand wildcards for segments:
        "splunk_configuration[*].hec_token": "splunk_configuration": unexpected
        wildcard usage
      reason: ReconcileError
      status: 'False'
      type: Synced`

### How can we reproduce it?
All existing DeliveryStream resources can't be synchronized. 
I've also tried to delete and then re-add the same resource.
Here a DeliveryStream example used:

`apiVersion: firehose.aws.upbound.io/v1beta1
kind: DeliveryStream
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-195"
  name: test
  namespace: test-namespace
spec:
  deletionPolicy: Delete
  forProvider:
    destination: extended_s3
    extendedS3Configuration:
      - bucketArn: arn:aws:s3:::test-bucket-zzz
        bufferInterval: 900
        bufferSize: 128
        dataFormatConversionConfiguration:
          - enabled: true
            inputFormatConfiguration:
              - deserializer:
                  - openXJsonSerDe:
                      - caseInsensitive: true
            outputFormatConfiguration:
              - serializer:
                  - parquetSerDe:
                      - compression: "GZIP"
            schemaConfiguration:
              - catalogId: "zzz"
                databaseName: 'db_name'
                region: eu-west-1
                tableName: 'table_name'
                versionId: LATEST
                roleArn: "arn:aws:iam::zzz:role/firehose-role"
        errorOutputPrefix: "error/!{firehose:error-output-type}/!{timestamp:'year='yyyy/'month='MM/'day='dd/'hour='HH/}"
        prefix: "!{timestamp:'year='yyyy/'month='MM/'day='dd/'hour='HH/}"
        roleArn: "arn:aws:iam::zzz:role/firehose-role"
    name: test
    region: eu-west-1
    tags:
      env: dev`

### What environment did it happen in?

* Crossplane Version: 1.14.0
* Provider Version: 0.46.0
* Kubernetes Version: Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.10-eks-4f4795d", GitCommit:"164dfb62db432c0b28a1fced3956256af68533b6", GitTreeState:"clean", BuildDate:"2023-10-20T23:21:27Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes Distribution: EKS

**Comment by sannaroby** [comment]
I think it could be fixed by [this](https://github.com/crossplane/upjet/pull/312).

**Comment by haarchri** [comment]
@sergenyalcin we need to bump upjet here ?

**Comment by erhancagirici** [comment]
@haarchri upjet was bumped at `v0.46.0` -> `v0.46.1`
@sannaroby this issue should be fixed already at `v0.46.1`. Could you try upgrading and check?

**Comment by sannaroby** [comment]
@erhancagirici unfortunately, even with version 0.46.1, I still get the same error, for "http_endpoint_configuration", "splunk_configuration", "redshift_configuration" (I've not defined this options in my resources).
I attach the complete error stack below:

`2023-12-27T14:18:45Z	DEBUG	provider-aws	Cannot observe external resource	{"controller": "managed/firehose.aws.upbound.io/v1beta1, kind=deliverystream", "request": {"name":"zzz"}, "uid": "4abd934d-8ec5-4387-af62-23c4003da301", "version": "505331231", "external-name": "arn:aws:firehose:eu-west-1:xxx:deliverystream/zzz", "error": "cannot get connection details: cannot get connection details: cannot expand wildcards: cannot expand wildcards for segments: \"http_endpoint_configuration[*].access_key\": \"http_endpoint_configuration\": unexpected wildcard usage", "errorVerbose": "cannot expand wildcards for segments: \"http_endpoint_configuration[*].access_key\": \"http_endpoint_configuration\": unexpected wildcard usage\ncannot expand wildcards\ngithub.com/crossplane/upjet/pkg/resource.GetSensitiveAttributes\n\tgithub.com/crossplane/upjet@v1.1.0-rc.0.0.20231218093147-9543be90ce6b/pkg/resource/sensitive.go:113\ngithub.com/crossplane/upjet/pkg/resource.GetConnectionDetails\n\tgithub.com/crossplane/upjet@v1.1.0-rc.0.0.20231218093147-9543be90ce6b/pkg/resource/sensitive.go:68\ngithub.com/crossplane/upjet/pkg/controller.(*noForkExternal).Observe\n\tgithub.com/crossplane/upjet@v1.1.0-rc.0.0.20231218093147-9543be90ce6b/pkg/controller/external_nofork.go:517\ngithub.com/crossplane/upjet/pkg/controller.(*noForkAsyncExternal).Observe\n\tgithub.com/crossplane/upjet@v1.1.0-rc.0.0.20231218093147-9543be90ce6b/pkg/controller/external_async_nofork.go:117\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v1.14.1/pkg/reconciler/managed/reconciler.go:903\ngithub.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v1.14.1/pkg/ratelimiter/reconciler.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227\nruntime.goexit\n\truntime/asm_amd64.s:1598\ncannot get connection details\ngithub.com/crossplane/upjet/pkg/resource.GetConnectionDetails\n\tgithub.com/crossplane/upjet@v1.1.0-rc.0.0.20231218093147-9543be90ce6b/pkg/resource/sensitive.go:70\ngithub.com/crossplane/upjet/pkg/controller.(*noForkExternal).Observe\n\tgithub.com/crossplane/upjet@v1.1.0-rc.0.0.20231218093147-9543be90ce6b/pkg/controller/external_nofork.go:517\ngithub.com/crossplane/upjet/pkg/controller.(*noForkAsyncExternal).Observe\n\tgithub.com/crossplane/upjet@v1.1.0-rc.0.0.20231218093147-9543be90ce6b/pkg/controller/external_async_nofork.go:117\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v1.14.1/pkg/reconciler/managed/reconciler.go:903\ngithub.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v1.14.1/pkg/ratelimiter/reconciler.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227\nruntime.goexit\n\truntime/asm_amd64.s:1598\ncannot get connection details\ngithub.com/crossplane/upjet/pkg/controller.(*noForkExternal).Observe\n\tgithub.com/crossplane/upjet@v1.1.0-rc.0.0.20231218093147-9543be90ce6b/pkg/controller/external_nofork.go:519\ngithub.com/crossplane/upjet/pkg/controller.(*noForkAsyncExternal).Observe\n\tgithub.com/crossplane/upjet@v1.1.0-rc.0.0.20231218093147-9543be90ce6b/pkg/controller/external_async_nofork.go:117\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v1.14.1/pkg/reconciler/managed/reconciler.go:903\ngithub.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v1.14.1/pkg/ratelimiter/reconciler.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227\nruntime.goexit\n\truntime/asm_amd64.s:1598"}`

**Comment by erhancagirici** [comment]
@sannaroby for the fix to be fully consumed, `crossplane-runtime` needed to be bumped also. That was done on `v0.47.0` , could you validate from your side that the issue is resolved?

**Comment by sannaroby** [comment]
@erhancagirici I've updated to v0.47.1 and this version fix the problems!
Thanks for your support.
